<?php

namespace Database\Seeders;

use App\Models\MBahanBaku;
use Illuminate\Database\Seeder;

class BahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // DAFTAR LENGKAP SEMUA PRODUK (GABUNGAN DATA 1 & 2)
        $semuaProduk = [
            "ALBATROS (INDOOR)",
            "ALBATROS FOTO (INDOOR)",
            "AMPLOP LINEN 21x15 (MIN 2BOX)",
            "AMPLOP PAPPERLINE 11x23 (MIN 2BOX)",
            "BACKLITE (OUTDOOR)",
            "BACKLITE JERMAN (UMUM)",
            "BAHAN KOSONG ALBATROS",
            "BAHAN KOSONG CLOTH BANNER",
            "BAHAN KOSONG FLEXY 280 GR",
            "BAHAN KOSONG GRAFTAC",
            "BAHAN KOSONG KOREA DOFF/GLOSSY 440 GR",
            "BAHAN KOSONG ONEWAY VISION",
            "BALIHO",
            "Biaya Penanganan Online",
            "BINGKAI KAYU (TRIPLEK+ALBATROS/PVC)",
            "BINGKAI KAYU (TRIPLEK+FLEXY 280)",
            "BINGKAI KAYU (TRIPLEK+KOREA 440)",
            "BINGKAI KAYU FLEXY 280 GR (TANPA TRIPLEK)",
            "BINGKAI KAYU KOREA DOFF/GLOSSY 440 GR (TANPA TRIPLEK)",
            "BOTOL INSERT PAPER MIN 24pcs",
            "BOTOL PLASTIK / My Bottle (1 WARNA) MIN 24pcs",
            "BOTOL STAINLESS (Tanpa Sablon) 1-12 Pcs",
            "BOTOL STAINLESS (Tanpa Sablon) 13-50 Pcs",
            "BOTOL STAINLESS (Tanpa Sablon) 51-100 Pcs",
            "BROSUR",
            "BUKU",
            "CAS DESAIN",
            "CLOTH BANNER (OUTDOOR)",
            "CUTTING STICKER (1 Warna)",
            "CUTTING STICKER (1 Warna) - Reseller",
            "CUTTING STICKER BONTAQ / VINYL ( < 5CM)",
            "CUTTING STICKER BONTAQ / VINYL (MIN.5CM)",
            "DECAL MOBIL",
            "DECAL SEPEDA MOTOR",
            "DECAL STICKER",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU ART PAPPER A3 (1 SISI)",
            "DOCU ART PAPPER A3 (2 SISI)",
            "DOCU STICKER BONTAQ GLOSSY/KERTAS (A3) 1-20",
            "DOCU STICKER BONTAQ GLOSSY/KERTAS (A3) 21-30",
            "DOCU STICKER BONTAQ GLOSSY/KERTAS (A3) 31-50",
            "DOCU STICKER BONTAQ GLOSSY/KERTAS (A3) 51-100",
            "DOCU STICKER BONTAQ GLOSSY/KERTAS (A3) 100-dst",
            "DOCU STICKER VINYL (A3) 1-10",
            "DOCU STICKER VINYL (A3) 11-20",
            "DOCU STICKER VINYL (A3) 21-30",
            "DOCU STICKER VINYL (A3) 31-50",
            "DOCU STICKER VINYL (A3) 51-100",
            "DOCU STICKER VINYL (A3) 100-Dst",
            "DTF (Direct Transfer Film) > 1 Meter",
            "DTF (Direct Transfer Film) < 1 Meter",
            "DTF Ukuran A3",
            "DTF Ukuran A4",
            "DURATRAN (INDOOR)",
            "ELECTRIC ROLL BANNER (Berdiri)",
            "ELECTRIC ROLL BANNER (Gantung)",
            "FLEXY 280 (MEMBER KHUSUS) MA/LS",
            "FLEXY 280 (OUTDOOR)",
            "FLEXY 280 ( OUTDOOR) CAB. BJM",
            "FLEXY 280 HIRES (OUTDOOR)",
            "FLEXY 280 HIRES (OUTDOOR) Cab.BJM",
            "FLEXY 340 (OUTDOOR)",
            "FLEXY 340 HIRES (OUTDOOR)",
            "GANCI KAKI",
            "GANTUGAN KUNCI (105-200) 5,8 CM",
            "GANTUNGAN KUNCI (1-25 PCS) 5,8 CM",
            "GANTUNGAN KUNCI (25-50 PCS) 5,8 CM",
            "GANTUNGAN KUNCI (51-105 PCS) 5,8 CM",
            "GANTUNGAN KUNCI (105-200 PCS) 5,8 CM",
            "GANTUNGAN KUNCI 4,5 CM (1-25 PCS)",
            "GANTUNGAN KUNCI 4,5 CM ( 25-50 PCS)",
            "GANTUNGAN KUNCI 4,5 CM (51-105 PCS)",
            "GANTUNGAN KUNCI 4,5 CM (105-200 PCS)",
            "GANTUNGAN KUNCI MIKA ACRYLIC",
            "GITAL DOKI",
            "GRAFIR SAJA",
            "HURUF LETTER NEON",
            "HURUF TIMBUL",
            "HVS",
            "ID CARD MIKA",
            "ID CARD MIKA + YOYO",
            "ID CARD MIKA + YOYO + LOGO (MIKA)",
            "ID CARD MIKA + YOYO + LOGO (STICKER)",
            "ID CARD PVC + YOYO + CASING",
            "ID CARD PVC + YOYO + LOGO (MIKA)",
            "ID CARD PVC + YOYO + LOGO (MIKA) + CASING",
            "ID CARD PVC + YOYO + LOGO (STICKER)",
            "ID CARD PVC + YOYO + LOGO (STICKER) + CASING",
            "ID CARD PVC DOCU ( > 100 PCS )",
            "ID CARD PVC DOCU (1pcs)",
            "ID CARD PVC DOCU (2-20 PCS )",
            "ID CARD PVC DOCU (21-50 PCS )",
            "ID CARD PVC DOCU (51-100 PCS )",
            "ID CARD PVC DOCU + CASING",
            "Infraboard Sheet/Impraboard + Stiker",
            "Infraboard Sheet/Impraboard + Stiker + Pola",
            "JILID HARD COVER (A4) 1-5",
            "JILID HARD COVER (A4) 6-KEATAS",
            "JILID HARD COVER (F4) 1-5",
            "JILID HARD COVER (F4) 6-KEATAS",
            "JILID KALENDER MEJA POTRAIT/LANSCAPE (1- 100 PCS)",
            "JILID KALENDER MEJA POTRAIT/LANSCAPE (100 PCS KEATAS)",
            "JILID SOFT COVER (A4) 1-5",
            "JILID SOFT COVER (A4) 6-KEATAS",
            "JILID SOFT COVER (F4) 1-5",
            "JILID SOFT COVER (F4) 6-KEATAS",
            "JOIN MEMBER Restu Guru Promosindo",
            "KALENDER",
            "KALKIR",
            "KANVAS (INDOOR)",
            "KAOS DTG",
            "KARTU NAMA 1 SISI (1 BOX)",
            "KARTU NAMA 1 SISI (2 BOX)",
            "KARTU NAMA 1 SISI + LAMINASI",
            "KARTU NAMA 2 SISI",
            "KARTU NAMA 2 SISI (1 BOX)",
            "KARTU NAMA 2 SISI + LAMINASI (1 SISI)",
            "KARTU NAMA 2 SISI + LAMINASI (2 SISI)",
            "KESALAHAN CETAK",
            "KIPAS",
            "KLEMSENG (1-50 PCS)",
            "KLEMSENG (51-100 PCS)",
            "KLEMSENG (101-200 PCS)",
            "KLEMSENG (201-300 PCS)",
            "KOREA DOFF 440 (OUTDOOR)",
            "KOREA DOFF 440 (OUTDOOR) - Reseller",
            "KOREA DOFF 440 HIRES (OUTDOOR)",
            "KOREA GLOSSY 440 (OUTDOOR)",
            "KOREA GLOSSY 440 (OUTDOOR) - Reseller",
            "KOREA GLOSSY 440 HIRES (OUTDOOR)",
            "KOTAK MUG",
            "KOTAK PLAKAT",
            "Lainnya",
            "LAMINASI DINGIN A3+ (1 SISI)",
            "LAMINASI DINGIN A3+ (2 SISI)",
            "LAMINASI KERTAS A3 AP 260/150 GR",
            "LAMINASI PANAS DOCU A3 ART PAPPER (1 SISI)",
            "LAMINASI PANAS DOCU A3 ART PAPPER (2 SISI)",
            "LAMINASI STICKER BONTAQ / VINYL A3",
            "LAMINATING (A4)",
            "LAMPU SOROT",
            "LANYARD 2 SISI + STOPPER (MIN. 12 PCS)",
            "LEAFLET",
            "LINEN A4 (1 SISI)",
            "LINEN A4 (2 SISI)",
            "LINEN F4 (1 SISI)",
            "LINEN F4 (2 SISI)",
            "LUBANG",
            "MAP",
            "MASKER SCUBA (MIN 100PCS)",
            "MIKA BENING 2MM + POTONG",
            "MIKA BENING 3MM + POTONG",
            "MIKA BENING 5MM + POTONG",
            "MIKA BENING 8MM + POTONG",
            "MIKA BENING 10MM + POTONG",
            "MIKA CERMIN/GOLD + POTONG",
            "MIKA SUSU 2MM + POTONG",
            "MIKA SUSU 3MM + POTONG",
            "MIKA SUSU 5MM + POTONG",
            "MIKA SUSU 8MM + POTONG",
            "MIKA SUSU 10MM + POTONG",
            "MINI BANNER ALBATROS (25X40)",
            "MINI BANNER ART PAPER (25X40)",
            "MINI BANNER FLEXY 280 (25X40)",
            "MINI BANNER FLEXY 280 (25X40) HIRES",
            "MINI BANNER FLEXY 340 (25X40)",
            "MINI BANNER FLEXY 340 (25X40) HIRES",
            "MINI BANNER KOREA (25X40)",
            "MINI BANNER PVC (25X40)",
            "MUG IMPORT (1-10 PCS)",
            "MUG IMPORT (11-20 PCS)",
            "MUG IMPORT (21-30 PCS)",
            "MUG IMPORT (31-50 PCS)",
            "MUG IMPORT (51-100 PCS)",
            "MUG IMPORT (100- dst)",
            "NEON BOX KOTAK + AKRILIK 3MM + STICKER (1 SISI)",
            "NEON BOX KOTAK + AKRILIK 3MM + STICKER (2 SISI)",
            "NEON BOX KOTAK + BACKLITE (1 SISI)",
            "NEON BOX KOTAK + BACKLITE (2 SISI)",
            "NEON BOX POLA + AKRILIK 3MM + STICKER (1 SISI)",
            "NEON BOX POLA + AKRILIK 3MM + STICKER (2 SISI)",
            "NEON BOX POLA + BACKLITE (1 SISI )",
            "NEON BOX POLA + BACKLITE (2 SISI )",
            "NOTA / KOP SURAT (NCR)",
            "ONEWAY STICKER (OUTDOOR)",
            "ONGKOS KIRIM BARANG",
            "ONGKOS POTONG SAJA (MIKA 2 - 5 MM)",
            "ONGKOS POTONG SAJA (MIKA 8 - 10 MM)",
            "OVAL FLOOR ROTARY WIND APORT (36X150) PO",
            "PACKAGING",
            "Pajak PPH",
            "Pajak PPN 11%",
            "PAJAK SKPD/SSPD",
            "PAKET BOTOL PLASTIK + POUCH (1WARNA) MIN 50pcs",
            "PANEL MIKA",
            "PAPAN NAMA (Billboard)",
            "PAPAN PLAT SENG BAHAN CUTTING",
            "PAPAN PLAT SENG BAHAN SPANDUK",
            "PAPAN PLAT SENG BAHAN STICKER",
            "PAPER BAG UK. A4 ( > 200 PCS)",
            "PAPER BAG UK. A4 (1-50 PCS)",
            "PAPER BAG UK. A4 (51-100 PCS)",
            "PAPER BAG UK. A4 (101-200 PCS)",
            "PAPPER BAG",
            "PEMASANGAN & INSTALASI",
            "PERFORASI",
            "PERFORASI (A3)",
            "PIN (1-25 PCS) 4,5cm",
            "PIN (26-50 PCS) 4,5 CM",
            "PIN (51-105 PCS) 4,5cm",
            "PIN (105-200 PCS) 4,5cm",
            "PIN / GANTUNGAN KUNCI (100pcs keatas) 7cm",
            "PIN / GANTUNGAN KUNCI (Min 12pcs) 7cm",
            "PIN / GANTUNGAN KUNCI (Min 100pcs) 7cm",
            "PIN 5,8 CM (1-25 PCS)",
            "PIN 5,8 CM (26 - 50 PCS)",
            "PIN 5,8 CM (51 - 105 PCS)",
            "PIN 5,8 CM (105-200 PCS )",
            "PLAKAT MIKA ACRYLIC (Tanpa Kotak)",
            "PLAKAT MIKA ACRYLIC + KOTAK",
            "PLONG KARTU NAMA",
            "POTONG KERTAS / STIKER UK. A4",
            "POTONG KERTAS / STIKER UK. A5",
            "POTONG KERTAS / STIKER UK. A6",
            "POTONG KERTAS / STIKER UKURAN < DARI A6",
            "POTONG KOTAK MULTIGRAFIKA",
            "POTONG MANUAL MULTIGRAFIKA",
            "POTONG POLA MULTIGRAFIKA",
            "PRESS KAOS BAGIAN DEPAN / BELAKANG",
            "PRESS KAOS BAGIAN LENGAN",
            "PRINTABLE",
            "Print UV Besar (Ukuran >20x20cm)",
            "Print UV Kecil (Ukuran min. 3x1cm)",
            "Print UV Sedang (Ukuran >10x10cm)",
            "PVC (INDOOR)",
            "PVC A4 (PRINTER) 1 SISI",
            "PVC A4 (PRINTER) 2 SISI",
            "PVC DOCU A4 (1 SISI)",
            "PVC DOCU A4 (2 SISI)",
            "PVC FOTO (INDOOR)",
            "Reseller FLEXY 280 (OUTDOOR) LS",
            "Reseller FLEXY 280 (OUTDOOR) MA",
            "ROLL BAHAN",
            "ROLL BANNER (60X160)",
            "ROLL BANNER (80X200)",
            "ROLL BANNER ALBATROS (60X160)",
            "ROLL BANNER ALBATROS (80X200)",
            "RUNNING TEXT 3 WARNA - PANEL KECIL (16cmX32cm) TANPA INSTALASI",
            "RUNNING TEXT FULL COLOUR (Per Panel) TANPA INSTALASI",
            "SABLON",
            "SABLON CUP 1 WARNA UK. 12-16 Oz ( MIN. 500 PCS )",
            "SABLON CUP 1 WARNA UK. 22 Oz ( MIN. 500 PCS )",
            "Sablon DTF Per CM",
            "SABLON PLASTIK OVAL OLSHOP UK. 20X30 (MIN. 1000 PCS)",
            "SABLON PLASTIK OVAL OLSHOP UK. 25X35 (MIN. 1000 PCS)",
            "SABLON PLASTIK OVAL OLSHOP UK. 30X40 (MIN. 1000 PCS)",
            "SABLON PLASTIK OVAL OLSHOP UK. 35X50 (MIN. 1000 PCS)",
            "SABLON PLASTIK OVAL OLSHOP UK. 36X38 (MIN. 1000 PCS)",
            "SABLON TAS KAIN TALI OVAL UK. 20X26 (MIN.100 PCS)",
            "SABLON TAS KAIN TALI OVAL UK. 25X35 (MIN.100 PCS)",
            "SABLON TAS KAIN TALI OVAL UK. 30X40 (MIN.100 PCS)",
            "SABLON TAS KAIN TALI PANJANG UK. 25X35X8 (MIN.100 PCS)",
            "SABLON TAS KAIN TALI PANJANG UK. 30X40X8 (MIN.100 PCS)",
            "SABLON TAS KAIN TALI PANJANG UK. 38X45X8 (MIN.100 PCS)",
            "SOLVENT OUTDOOR",
            "SPIRAL (Per Mata)",
            "SPIRAL KALENDER DINDING ( > 100 PCS)",
            "SPIRAL KALENDER DINDING ( < 100 PCS)",
            "STEMPEL",
            "STEMPEL Member",
            "STEMPEL Reseller",
            "STEMPEL TAMBAH WARNA",
            "STICKER BLACKOUT (INDOOR)",
            "STICKER CINA (INDOOR)",
            "STICKER CINA (OUTDOOR)",
            "STICKER GRAFTAC (INDOOR)",
            "STICKER GRAFTAC (OUTDOOR)",
            "STICKER GRAFTAC/RITRAMA (INDOOR) + CUT MANUAL",
            "STICKER GRAFTAC/RITRAMA (INDOOR) + CUT MESIN",
            "STICKER GRAFTAC/RITRAMA (INDOOR) + LAMINASI",
            "STICKER ORAJET (INDOOR)",
            "STICKER ORAJET (OUTDOOR)",
            "STICKER RITRAMA (INDOOR)",
            "STICKER SUNBLAST + CUTTING",
            "STICKER SUNBLAST + CUTTING Member",
            "STICKER SUNBLAST + CUTTING Reseller",
            "STICKER SUNBLAST + PRINT (INDOOR)",
            "STICKER TRANSPARANT (INDOOR)",
            "TAMBAH NUMERATOR (NOTA NCR)",
            "TAMBAH WARNA LOGO (BESAR) (NOTA NCR)",
            "TAMBAH WARNA LOGO (KECIL) (NOTA NCR)",
            "TAMBAH WARNA SABLON TAS / BOTOL",
            "TAS SPUNBOND 20cm x 30cm (1 Warna) SISI LEBAR (MIN 50Pcs)",
            "TAS SPUNBOND 20cm x 30cm (1 Warna) SISI PRES (MIN 50Pcs)",
            "TAS SPUNBOND 30cm x 40cm (1 Warna) SISI LEBAR (MIN 50Pcs)",
            "TAS SPUNBOND 30cm x 40cm (1 Warna) SISI PRES (MIN 50Pcs)",
            "T BANNER",
            "TENDA (3m x 3m) BAHAN KOREA 440",
            "TENDA (3m x 3m) BAHAN PARASOIL STANDARD",
            "TENDA (3m x 4m) BAHAN KOREA 440",
            "TENDA (3m x 4m) BAHAN PARASOIL STANDARD",
            "TIANG 2 INC",
            "TIANG 2,5 INC",
            "TIANG 3 INC",
            "TIANG 3,5 INC",
            "TIANG 4 INC",
            "TIANG 5 INC",
            "TIANG MINI X BANNER",
            "TIANG ROLL BANNER (60X160)",
            "TIANG ROLL BANNER (80X200)",
            "TIANG X BANNER (60X160)",
            "TIANG X BANNER (80X180)",
            "TIANG Y BANNER (60X160)",
            "TIANG Y BANNER (80X180)",
            "TINTA OUTDOOR (SOLVENT)",
            "TRIPOD BANNER",
            "UNDANGAN BLANKO",
            "UNDANGAN HARD COVER",
            "UNDANGAN SOFT COVER",
            "X BANNER ALBATROS (60X160)",
            "X BANNER FLEXY 280 (60X160)",
            "X BANNER FLEXY 280 (60X160) HIRES",
            "X BANNER FLEXY 280 (80X180)",
            "X BANNER FLEXY 280 (80X180) HIRES",
            "X BANNER FLEXY 340 (60X160)",
            "X BANNER FLEXY 340 (60X160) HIRES",
            "X BANNER FLEXY 340 (80X180)",
            "X BANNER FLEXY 340 (80X180) HIRES",
            "X BANNER JUMBO (80X200)",
            "X BANNER KOREA (60X160)",
            "X BANNER KOREA (80X180)",
            "X BANNER PVC (60X160)",
            "Y BANNER ALBATROS (60X160)",
            "Y BANNER ALBATROS (80X180)",
            "Y BANNER FLEXY 280 (60X160)",
            "Y BANNER FLEXY 280 (60X160) HIRES",
            "Y BANNER FLEXY 280 (80X180)",
            "Y BANNER FLEXY 280 (80X180) HIRES",
            "Y BANNER FLEXY 340 (60X160)",
            "Y BANNER FLEXY 340 (60X160) HIRES",
            "Y BANNER FLEXY 340 (80X180)",
            "Y BANNER FLEXY 340 (80X180) HIRES",
            "Y BANNER KOREA (60X160)",
            "Y BANNER KOREA (80X180)",
            "Y BANNER PVC (60X160)",
            "Y BANNER PVC (80X180)"
        ];

        // Memanggil fungsi untuk insert data
        self::addBahanBaku($semuaProduk);
    }

    /**
     * Fungsi helper untuk insert data
     */
    public static function addBahanBaku(array $produkList): void
    {
        foreach ($produkList as $index => $namaProduk) {
            // Generate Kode Bahan Otomatis: PRD-001, PRD-002, dst.
            // str_pad berguna untuk membuat angka 001, 010, 100 agar rapi
            $kodeOtomatis = 'PRD-' . str_pad($index + 1, 3, '0', STR_PAD_LEFT);

            MBahanBaku::firstOrCreate(
                ['nama_bahan' => $namaProduk], // Cek berdasarkan nama agar tidak duplikat
                ['kode_bahan' => $kodeOtomatis] // Isi kode jika baru dibuat
            );
        }
    }
}
