<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GudangBarangSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [

            // ========================
            // DATA BARANG
            // ========================

            ['nama_bahan'=>'ALBATROS','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'AMPLOP LINEN','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BACKLITE 510 gsm','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BALIHO','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TRIPLEK','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BOTOL INSERT PAPER MIN 24pcs','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BOTOL PLASTIK / My Bottle (1 WARNA) MIN 24pcs','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BOTOL STAINLESS','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BROSUR','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'BUKU','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'CAS DESAIN','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'CLOTH BANNER/SATIN','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'CUTTING STICKER','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'CUTTING STICKER BONTAQ / VINYL','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'DECAL MOBIL','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'DECAL SEPEDA MOTOR','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'DECAL STICKER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'DOCU ART PAPPER A3 (2 SISI)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'DOCU STICKER BONTAQ GLOSSY/KERTAS (A3)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM per november 2022'],
            ['nama_bahan'=>'DOCU STICKER VINYL (A3)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM per november 2022'],
            ['nama_bahan'=>'DTF (Direct Transfer Film)','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'DTF Ukuran A3','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'DTF Ukuran A4','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'DURATRAN','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ELECTRIC ROLL BANNER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'FLEXY 280 gsm','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'FLEXY 340 gsm','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GANCI KAKI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GANTUGAN KUNCI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GANTUNGAN KUNCI 4,5 CM','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GANTUNGAN KUNCI MIKA ACRYLIC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GITAL DOKI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'GRAFIR SAJA','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'HURUF LETTER NEON','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'HURUF TIMBUL','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'HVS','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ID CARD MIKA','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ID CARD MIKA + YOYO','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ID CARD PVC + YOYO + CASING','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'JILID HARD COVER (A4)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'JILID HARD COVER (F4)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KALENDER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KALKIR','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KANVAS','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KAOS DTG','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KARTU NAMA 1 SISI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KARTU NAMA 2 SISI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KIPAS','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KLEMSENG','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KOREA DOFF 440 gsm','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KOREA GLOSSY 440','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'KOTAK MUG','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'LAMINASI DINGIN A3+ (1 SISI)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'LAMPU SOROT','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'LANYARD 2 SISI + STOPPER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'LEAFLET','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MAP','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MASKER SCUBA','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA BENING 2MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA BENING 3MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA BENING 5MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA BENING 8MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA BENING 10MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA CERMIN/GOLD + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA SUSU 2MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA SUSU 3MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA SUSU 5MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MIKA SUSU 8MM + POTONG','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'MINI BANNER ALBATROS (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER ART PAPER (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER FLEXY 280 (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER FLEXY 340 (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER FLEXY 280 (25X40) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER FLEXY 340 (25X40) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER KOREA (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MINI BANNER PVC (25X40)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'MUG IMPORT','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'NEON BOX KOTAK + AKRILIK 3MM + STICKER','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'NEON BOX KOTAK + BACKLITE','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'NEON BOX POLA + AKRILIK 3MM + STICKER','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'NOTA / KOP SURAT (NCR)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ONEWAY STICKER','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAKET BOTOL PLASTIK + POUCH (1WARNA)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PANEL MIKA','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPAN NAMA (Billboard)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPAN PLAT SENG BAHAN CUTTING','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPAN PLAT SENG BAHAN SPANDUK','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPAN PLAT SENG BAHAN STICKER','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPER BAG UK. A4','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PAPPER BAG','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PERFORASI','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PERFORASI (A3)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PIN 4,5cm','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PIN / GANTUNGAN KUNCI 7cm','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PIN 5,8 CM','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PLAKAT MIKA ACRYLIC','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PLAKAT MIKA ACRYLIC + KOTAK','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PLONG KARTU NAMA','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PRESS KAOS BAGIAN DEPAN / BELAKANG','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PRESS KAOS BAGIAN LENGAN','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PRINTABLE','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Print UV Besar (Ukuran >20x20cm)','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Print UV Kecil (Ukuran min. 3x1cm)','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Print UV Sedang (Ukuran >10x10cm)','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PVC','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PVC A4 (PRINTER) 1 SISI','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PVC DOCU A4 (1 SISI)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'PVC FOTO','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Reseller FLEXY 280 LS','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Reseller FLEXY 280 MA','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ROLL BAHAN','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ROLL BANNER (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ROLL BANNER (80X200)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ROLL BANNER ALBATROS (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'ROLL BANNER ALBATROS (80X200)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'RUNNING TEXT 3 WARNA - PANEL KECIL (16cmX32cm) TANPA INSTALASI','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'RUNNING TEXT FULL COLOUR (Per Panel) TANPA INSTALASI','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON CUP 1 WARNA UK. 12-16 Oz ( MIN. 500 PCS )','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON CUP 1 WARNA UK. 22 Oz ( MIN. 500 PCS )','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Sablon DTF Per CM','satuan'=>'CENTIMETER','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON PLASTIK OVAL OLSHOP UK. 20X30','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON PLASTIK OVAL OLSHOP UK. 25X35','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON PLASTIK OVAL OLSHOP UK. 30X40','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON PLASTIK OVAL OLSHOP UK. 35X50','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON PLASTIK OVAL OLSHOP UK. 36X38','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI OVAL UK. 20X26','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI OVAL UK. 25X35','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI OVAL UK. 30X40','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI PANJANG UK. 25X35X8','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI PANJANG UK. 30X40X8','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SABLON TAS KAIN TALI PANJANG UK. 38X45X8','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SOLVENT','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SPIRAL (Per Mata)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'SPIRAL KALENDER DINDING ( > 100 PCS)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'STEMPEL','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'STEMPEL Member','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'STEMPEL Reseller','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TAMBAH WARNA LOGO (BESAR)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TAMBAH WARNA LOGO (KECIL)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TAMBAH WARNA SABLON TAS / BOTOL','satuan'=>'ITEM','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TAS SPUNBOND 20cm x 30cm (1 Warna) SISI LEBAR','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TAS SPUNBOND 30cm x 40cm (1 Warna) SISI LEBAR','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'T BANNER','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TENDA (3m x 3m) BAHAN KOREA 440','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TENDA (3m x 4m) BAHAN PARASOIL STANDARD','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 2 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 2,5 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 3 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 3,5 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 4 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG 5 INC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG MINI X BANNER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG ROLL BANNER (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG ROLL BANNER (80X200)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG X BANNER (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG X BANNER (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG Y BANNER (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TIANG Y BANNER (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TINTA OUTDOOR (SOLVENT)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'TRIPOD BANNER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'UNDANGAN BLANKO','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'UNDANGAN HARD COVER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'UNDANGAN SOFT COVER','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER ALBATROS (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 280 (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 280 (60X160) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 280 (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 280 (80X180) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 340 (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 340 (60X160) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 340 (80X180)','satuan'=>'PAKET','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER FLEXY 340 (80X180) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER JUMBO (80X200)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER KOREA (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER KOREA (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'X BANNER PVC (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER ALBATROS (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER ALBATROS (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 280 (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 280 (60X160) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 280 (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 280 (80X180) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 340 (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 340 (60X160) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 340 (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER FLEXY 340 (80X180) HIRES','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER KOREA (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER KOREA (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER PVC (60X160)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'Y BANNER PVC (80X180)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>'UMUM'],
            ['nama_bahan'=>'STIKER SCOTLITE','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'STIKER ORACAL','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'STIKER VINYL GRAFTAC','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'STIKER VINYL A3','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'STIKER BONTAK KERTAS (DOFF)','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'STIKER BONTAK GLOSSY','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 120','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 150','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 190','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 210','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 230','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'ART PAPER 260','satuan'=>'PCS','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],
            ['nama_bahan'=>'BACKLITE JERMAN 510 gsm','satuan'=>'METER','stok'=>0,'batas_stok'=>1000,'keterangan'=>null],

        ];

        foreach ($data as $item) {
            DB::table('gudang_barangs')->updateOrInsert(
                ['nama_bahan' => $item['nama_bahan']],
                [
                    'kategori_id' => null,
                    'harga' => 0,
                    'satuan' => $item['satuan'],
                    'stok' => $item['stok'],
                    'batas_stok' => $item['batas_stok'],
                    'keterangan' => $item['keterangan'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
